#!/bin/bash

if [ $# -ne "2" ]
then
    echo "Ожидается 2 параметра"
    echo "Пример использования: formatPartition md10 1"
    exit
fi


raidName=$1
partitionNo=$2
partitionName=${1}p${2}

hasExt4=`lsblk -f | grep $partitionName | grep ext4 | wc -l`
if [ $hasExt4 -ge 1 ] 
then
    echo "Partition '$partitionName' already has file system ext4"
    exit
fi

mkfs.ext4 /dev/$partitionName
