---
- name: Prepare server
  hosts: all
  become: true
  vars:
    raidName: md127
    disk0: sdc
    disk1: sdd
    disk2: sde
    disk3: sdf
  tasks:
    - block:
        - command: lsblk
          register: blk
        - name: List block devices
          debug: 
            var: blk.stdout_lines


    - block:
        - name: Create RAID-10 of 4 disks
          command: chdir=/vagrant bash createRaid10 {{ raidName }} {{ disk0 }} {{ disk1 }} {{ disk2 }} {{ disk3 }}
          register: info

        - name: Create result
          debug: 
            var: info.stdout_lines

    - block:
        - command: lsblk
          register: blk
        - name: List block devices
          debug: 
            var: blk.stdout_lines

    - block:
        - command: mdadm -D /dev/{{ raidName }}
          register: info
        - name: Show {{ raidName }} details
          debug: 
            var: info.stdout_lines


    - block:
        - name: Set disk FAILED at RAID
          command: chdir=/vagrant bash setHddFailed {{ raidName }} {{ disk0 }}
          register: info

        - name: Set disk FAILED at RAID result
          debug: 
            var: info.stdout_lines

    - block:
        - command: mdadm -D /dev/{{ raidName }}
          register: info
        - name: Show {{ raidName }} details
          debug: 
            var: info.stdout_lines

    - block:
        - name: Examine disk
          command: chdir=/vagrant bash examineHdd {{ disk0 }}
          register: info

        - name: Examine disk result
          debug: 
            var: info.stdout_lines

    - block:
        - name: Remove disk from RAID
          command: chdir=/vagrant bash removeHddFromRaid {{ raidName }} {{ disk0 }}
          register: info

        - name: Remove disk from RAID result
          debug: 
            var: info.stdout_lines

    - block:
        - command: mdadm --zero-superblock /dev/{{ disk0 }}
          register: info
        - name: zero-superblock /dev/{{ disk0 }}
          debug: 
            var: info.stderr

    - block:
        - command: mdadm /dev/{{ raidName }} --add /dev/{{ disk0 }}
          register: info
        - name: mdadm add /dev/{{ disk0 }}
          debug: 
            var: info.stderr

    - block:
        - command: mdadm -D /dev/{{ raidName }}
          register: info
        - name: Show {{ raidName }} details
          debug: 
            var: info.stdout_lines

    - command: fdisk -l /dev/{{ raidName }}
      register: info
    - name: fdisk -l
      debug: 
        var: info.stdout_lines

    - block:
        - name: Create partition 1
          command: chdir=/vagrant bash createPart {{ raidName }} 1
          register: info

        - name: Create partition 1 result
          debug: 
            var: info.stdout_lines

    - block:
        - name: Create partition 2
          command: chdir=/vagrant bash createPart {{ raidName }} 2
          register: info

        - name: Create partition 2 result
          debug: 
            var: info.stdout_lines

    - block:
        - name: Create partition 3
          command: chdir=/vagrant bash createPart {{ raidName }} 3
          register: info

        - name: Create partition 3 result
          debug: 
            var: info.stdout_lines

    - block:
        - name: Create partition 4
          command: chdir=/vagrant bash createPart {{ raidName }} 4
          register: info

        - name: Create partition 4 result
          debug: 
            var: info.stdout_lines

    - block:
        - name: Create partition 5
          command: chdir=/vagrant bash createPart {{ raidName }} 5
          register: info

        - name: Create partition 5 result
          debug: 
            var: info.stdout_lines

    - command: fdisk -l /dev/{{ raidName }}
      register: info
    - name: fdisk -l
      debug: 
        var: info.stdout_lines

    - block:
        - name: Format partition 1
          command: chdir=/vagrant bash formatPartition {{ raidName }} 1
          register: info

        - name: Create partition 1 result
          debug: 
            var: info.stdout_lines

    - block:
        - name: Format partition 2
          command: chdir=/vagrant bash formatPartition {{ raidName }} 2
          register: info

        - name: Create partition 2 result
          debug: 
            var: info.stdout_lines

    - block:
        - name: Format partition 3
          command: chdir=/vagrant bash formatPartition {{ raidName }} 3
          register: info

        - name: Create partition 3 result
          debug: 
            var: info.stdout_lines

    - block:
        - name: Format partition 4
          command: chdir=/vagrant bash formatPartition {{ raidName }} 4
          register: info

        - name: Create partition 4 result
          debug: 
            var: info.stdout_lines

    - block:
        - name: Format partition 5
          command: chdir=/vagrant bash formatPartition {{ raidName }} 5
          register: info

        - name: Create partition 5 result
          debug: 
            var: info.stdout_lines

    - command: lsblk -f
      register: info
    - name: fdisk -l
      debug: 
        var: info.stdout_lines

    - name: Create mount folder 1
      ansible.builtin.file:
        path: /mnt/data1
        state: directory

    - name: Create mount folder 2
      ansible.builtin.file:
        path: /mnt/data2
        state: directory

    - name: Create mount folder 3
      ansible.builtin.file:
        path: /mnt/data3
        state: directory

    - name: Create mount folder 4
      ansible.builtin.file:
        path: /mnt/data4
        state: directory

    - name: Create mount folder 5
      ansible.builtin.file:
        path: /mnt/data5
        state: directory

    - command: df -hT
      register: info
    - name: df -hT
      debug: 
        var: info.stdout_lines


    - shell: mdadm --detail --scan --verbose >> /etc/mdadm/mdadm.conf

    - name: Mount hdd 1
      ansible.posix.mount:
        path: /mnt/data1
        src: /dev/{{ raidName }}p1
        fstype: ext4
        state: present

    - name: Mount hdd 2
      ansible.posix.mount:
        path: /mnt/data2
        src: /dev/{{ raidName }}p2
        fstype: ext4
        state: present

    - name: Mount hdd 3
      ansible.posix.mount:
        path: /mnt/data3
        src: /dev/{{ raidName }}p3
        fstype: ext4
        state: present

    - name: Mount hdd 4
      ansible.posix.mount:
        path: /mnt/data4
        src: /dev/{{ raidName }}p4
        fstype: ext4
        state: present

    - name: Mount hdd 5
      ansible.posix.mount:
        path: /mnt/data5
        src: /dev/{{ raidName }}p5
        fstype: ext4
        state: present

    - name: Mount -a
      command: mount -a

    - command: cat /etc/mdadm/mdadm.conf
      register: info
    - name: cat /etc/mdadm/mdadm.conf
      debug: 
        var: info.stdout_lines
    