---
- name: Prepare server
  hosts: all
  become: true
  tasks:
    - block:
        - command: lsblk
          register: blk
        - name: List block devices
          debug: 
            var: blk.stdout_lines


    - block:
        - name: Create RAID-10 of 4 disks
          command: chdir=/vagrant bash createRaid10 md127 sdc sdd sde sdf
          register: md127

        - name: Create result
          debug: 
            var: md127.stdout_lines

    - block:
        - command: lsblk
          register: blk
        - name: List block devices
          debug: 
            var: blk.stdout_lines

    - block:
        - command: mdadm -D /dev/md127
          register: md127
        - name: Show md127 details
          debug: 
            var: md127.stdout_lines


    - block:
        - name: Set disk FAILED at RAID
          command: chdir=/vagrant bash setHddFailed md127 sdc
          register: md127

        - name: Set disk FAILED at RAID result
          debug: 
            var: md127.stdout_lines

    - block:
        - command: mdadm -D /dev/md127
          register: md127
        - name: Show md127 details
          debug: 
            var: md127.stdout_lines

    - block:
        - name: Examine disk
          command: chdir=/vagrant bash examineHdd sdc
          register: md127

        - name: Examine disk result
          debug: 
            var: md127.stdout_lines

    - block:
        - name: Remove disk from RAID
          command: chdir=/vagrant bash removeHddFromRaid md127 sdc
          register: md127

        - name: Remove disk from RAID result
          debug: 
            var: md127.stdout_lines

    - block:
        - command: mdadm --zero-superblock /dev/sdc
          register: md127
        - name: zero-superblock /dev/sdc
          debug: 
            var: md127.stderr

    - block:
        - command: mdadm /dev/md127 --add /dev/sdc
          register: md127
        - name: mdadm add /dev/sdc
          debug: 
            var: md127.stderr

    - block:
        - command: mdadm -D /dev/md127
          register: md127
        - name: Show md127 details
          debug: 
            var: md127.stdout_lines

    - command: fdisk -l /dev/md127
      register: md127
    - name: fdisk -l
      debug: 
        var: md127.stdout_lines

    - block:
        - name: Create partition 1
          command: chdir=/vagrant bash createPart md127 1
          register: md127

        - name: Create partition 1 result
          debug: 
            var: md127.stdout_lines

    - block:
        - name: Create partition 2
          command: chdir=/vagrant bash createPart md127 2
          register: md127

        - name: Create partition 2 result
          debug: 
            var: md127.stdout_lines

    - block:
        - name: Create partition 3
          command: chdir=/vagrant bash createPart md127 3
          register: md127

        - name: Create partition 3 result
          debug: 
            var: md127.stdout_lines

    - block:
        - name: Create partition 4
          command: chdir=/vagrant bash createPart md127 4
          register: md127

        - name: Create partition 4 result
          debug: 
            var: md127.stdout_lines

    - block:
        - name: Create partition 5
          command: chdir=/vagrant bash createPart md127 5
          register: md127

        - name: Create partition 5 result
          debug: 
            var: md127.stdout_lines

    - command: fdisk -l /dev/md127
      register: md127
    - name: fdisk -l
      debug: 
        var: md127.stdout_lines

    - block:
        - name: Format partition 1
          command: chdir=/vagrant bash formatPartition md127 1
          register: md127

        - name: Create partition 1 result
          debug: 
            var: md127.stdout_lines

    - block:
        - name: Format partition 2
          command: chdir=/vagrant bash formatPartition md127 2
          register: md127

        - name: Create partition 2 result
          debug: 
            var: md127.stdout_lines

    - block:
        - name: Format partition 3
          command: chdir=/vagrant bash formatPartition md127 3
          register: md127

        - name: Create partition 3 result
          debug: 
            var: md127.stdout_lines

    - block:
        - name: Format partition 4
          command: chdir=/vagrant bash formatPartition md127 4
          register: md127

        - name: Create partition 4 result
          debug: 
            var: md127.stdout_lines

    - block:
        - name: Format partition 5
          command: chdir=/vagrant bash formatPartition md127 5
          register: md127

        - name: Create partition 5 result
          debug: 
            var: md127.stdout_lines

    - command: lsblk -f
      register: md127
    - name: fdisk -l
      debug: 
        var: md127.stdout_lines

    - name: Create mount folder 1
      ansible.builtin.file:
        path: /mnt/data1
        state: directory

    - name: Create mount folder 2
      ansible.builtin.file:
        path: /mnt/data2
        state: directory

    - name: Create mount folder 3
      ansible.builtin.file:
        path: /mnt/data3
        state: directory

    - name: Create mount folder 4
      ansible.builtin.file:
        path: /mnt/data4
        state: directory

    - name: Create mount folder 5
      ansible.builtin.file:
        path: /mnt/data5
        state: directory

    - command: df -hT
      register: md127
    - name: df -hT
      debug: 
        var: md127.stdout_lines


    - shell: mdadm --detail --scan --verbose >> /etc/mdadm/mdadm.conf

    - name: Mount hdd 1
      ansible.posix.mount:
        path: /mnt/data1
        src: /dev/md127p1
        fstype: ext4
        state: present

    - name: Mount hdd 2
      ansible.posix.mount:
        path: /mnt/data2
        src: /dev/md127p2
        fstype: ext4
        state: present

    - name: Mount hdd 3
      ansible.posix.mount:
        path: /mnt/data3
        src: /dev/md127p3
        fstype: ext4
        state: present

    - name: Mount hdd 4
      ansible.posix.mount:
        path: /mnt/data4
        src: /dev/md127p4
        fstype: ext4
        state: present

    - name: Mount hdd 5
      ansible.posix.mount:
        path: /mnt/data5
        src: /dev/md127p5
        fstype: ext4
        state: present

    - name: Mount -a
      command: mount -a

    - command: cat /etc/mdadm/mdadm.conf
      register: md127
    - name: cat /etc/mdadm/mdadm.conf
      debug: 
        var: md127.stdout_lines
    