---
- name: Prepare server
  hosts: all
  become: true
  vars:
    raidName: md127
    disk0: sdc
    disk1: sdd
    disk2: sde
    disk3: sdf
  roles:
    - create_raid
    - create_partitions
    - format_partitions
    - create_mount_folders
    - mount_partitions
