---
- name: Create mount folders
  vars: 
    i: [1,2,3,4,5]
  file:
    path: /mnt/data{{ item }}
    state: directory
  loop: "{{ i }}"

- command: df -hT
  register: info
- name: df -hT
  debug: 
    var: info.stdout_lines

