// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'UpdatePasswordForm': string;
  'error': string;
}
export const cssExports: CssExports;
export default cssExports;
