---
- name: Create partitions
  vars: 
    i: [1,2,3,4,5]
  include_tasks: "create_partition.yml"    
  loop: "{{ i }}"

- command: fdisk -l /dev/{{ raidName }}
  register: info
- name: fdisk -l
  debug: 
    var: info.stdout_lines



