// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Header': string;
  'blue': string;
  'color': string;
  'grey': string;
  'language': string;
  'login': string;
  'logo': string;
  'menu': string;
  'profile': string;
}
export const cssExports: CssExports;
export default cssExports;
