// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'EditProductForm': string;
  'buttons': string;
  'error': string;
}
export const cssExports: CssExports;
export default cssExports;
