---
- name: Create mount folders
  vars: 
    i: [1,2,3,4,5]
  ansible.posix.mount:
    path: /mnt/data1
    src: /dev/{{ raidName }}p{{ item }}
    fstype: ext4
    state: present
  loop: "{{ i }}"

- name: Mount -a
  command: mount -a

- command: cat /etc/mdadm/mdadm.conf
  register: info
- name: cat /etc/mdadm/mdadm.conf
  debug: 
    var: info.stdout_lines
