// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Header': string;
  'blue': string;
  'grey': string;
}
export const cssExports: CssExports;
export default cssExports;
