// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'DetailedProductCard': string;
  'addToCart': string;
  'blue': string;
  'category': string;
  'defaultImage': string;
  'description': string;
  'grey': string;
  'header': string;
  'image': string;
  'info': string;
  'main': string;
  'price': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
