// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CategoriesPage': string;
  'categoryList': string;
  'curCategory': string;
}
export const cssExports: CssExports;
export default cssExports;
