// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appBut': string;
  'bg': string;
  'brick': string;
  'bt': string;
  'btGo': string;
  'btLoad': string;
  'categories': string;
  'coin': string;
  'content': string;
  'count': string;
  'cur': string;
  'develop': string;
  'editControls': string;
  'editInventory': string;
  'editorUI': string;
  'enterLogin': string;
  'finishLevelScreen': string;
  'gameOverScreen': string;
  'gameStats': string;
  'gold': string;
  'introScreen': string;
  'inventory': string;
  'level': string;
  'li': string;
  'pretty': string;
  'red': string;
  'save': string;
  'screen': string;
  'space': string;
  'stairs': string;
  'statsCoins': string;
  'statsLevel': string;
  'statsSteps': string;
  'statsTime': string;
  'tgLogin': string;
  'timer': string;
  'tip': string;
  'win': string;
  'wrapGame': string;
  'wrapLoad': string;
}
export const cssExports: CssExports;
export default cssExports;
