// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'guardCtrl2': string;
  'guardianControls': string;
  'manCtrl2': string;
  'playerControls': string;
  'ui': string;
  'uiOptions': string;
}
export const cssExports: CssExports;
export default cssExports;
