---
- name: Format partitions
  vars: 
    i: [1,2,3,4,5]
  include_tasks: "format_partition.yml"    
  loop: "{{ i }}"

- command: lsblk -f
  register: info
- name: fdisk -l
  debug: 
    var: info.stdout_lines

