// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CartItem': string;
  'blue': string;
  'btRemove': string;
  'defaultImage': string;
  'grey': string;
  'image': string;
  'info': string;
  'price': string;
  'quantity': string;
  'remove': string;
  'title': string;
  'total': string;
}
export const cssExports: CssExports;
export default cssExports;
