// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ProfilePage': string;
  'total': string;
}
export const cssExports: CssExports;
export default cssExports;
