// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ProductCard': string;
  'buyButton': string;
  'defaultImage': string;
  'description': string;
  'details': string;
  'image': string;
  'price': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
