// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ProductsPage': string;
  'menu': string;
  'menuItem': string;
}
export const cssExports: CssExports;
export default cssExports;
