services:
  project-db-source:
    image: mysql:8.0
    command: "--log-bin"
    container_name: project-db-source
    restart: always
      
    volumes:
      - ./project-db-source/mysql-secrets:/run/secrets
      - ./project-db-source/mysql-db:/var/lib/mysql
      - ./project-db-source/mysql-init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./project-db-source/mysql-conf:/etc/mysql/conf.d

    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root

    ports:
      - '192.168.10.151:3306:3306' 

    networks:
      - project_network         

  project-db-replica:
    image: mysql:8.0
    command: "--log-bin"
    container_name: project-db-replica
    # restart: always
    depends_on: 
      - project-db-source
      
    volumes:
      - ./project-db-replica/mysql-secrets:/run/secrets
      - ./project-db-replica/mysql-db:/var/lib/mysql
      - ./project-db-replica/mysql-init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./project-db-replica/mysql-conf:/etc/mysql/conf.d

    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root

    ports:
      - '192.168.10.152:3306:3306' 

    networks:
      - project_network         

networks:
  project_network:
    driver: bridge    