Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false  

  config.vm.hostname = "vagrantAnsibleNginx"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrantAnsibleNginx"
    vb.cpus = "2"
    vb.memory = "1024"
  end

  config.vm.provision "ansible", run: "always" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbook.yml"
    ansible.limit = "all"
  end

end
