Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false  

  config.vm.hostname = "vagrantAnsibleNginx"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrantAnsibleNginx"
    vb.cpus = "2"
    vb.memory = "1024"
  end


  config.vm.provision "shell", inline: <<-SHELL
    line="---------------------------------------"
    sudo apt install curl gnupg2 ca-certificates lsb-release ubuntu-keyring
    echo $line
    echo $line
    echo $line
    curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor \
    | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
    echo $line
    echo $line
    echo $line
    gpg --dry-run --quiet --no-keyring --import --import-options import-show /usr/share/keyrings/nginx-archive-keyring.gpg
    echo $line
    echo $line
    echo $line
    echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" \
    | sudo tee /etc/apt/sources.list.d/nginx.list
    echo $line
    echo $line
    echo $line
    sudo apt update
    echo $line
    echo $line
    echo $line
    sudo apt install nginx
    echo $line
    echo $line
    echo $line
    sudo cp /vagrant/default.conf /etc/nginx/conf.d/default.conf
    sudo systemctl start nginx
    echo $line
    echo $line
    echo $line
    sudo ss -ntlp
    echo $line
    echo $line
    echo $line
    curl localhost:8080
    echo $line
    echo $line
    echo $line
  SHELL
end
