Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false  

  config.vm.define 'nginx' do |machine|
    machine.vm.hostname = "vagrantAnsibleNginx"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "vagrantAnsibleNginx"
      vb.cpus = "2"
      vb.memory = "1024"
    end
      
    machine.vm.provision :ansible_local, run: "always" do |ansible|
      ansible.compatibility_mode = "2.0"

      ansible.playbook = "playbook.yml"
      ansible.install        = true
      ansible.limit          = "all"
      ansible.inventory_path = "inventory.ini"
    end
  end
end
