// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'BtToBasket': string;
  'basket': string;
  'blue': string;
  'grey': string;
  'input': string;
  'minus': string;
  'plus': string;
}
export const cssExports: CssExports;
export default cssExports;
