// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'LoginForm': string;
  'error': string;
  'loginRegister': string;
}
export const cssExports: CssExports;
export default cssExports;
