// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Modal': string;
  'closeButton': string;
  'content': string;
  'window': string;
}
export const cssExports: CssExports;
export default cssExports;
