name: GOL build-test-deploy
on:
  push:
    branches: [ react-hw4 ]
#  pull_request:
#    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  GOL-build-test-deploy:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache NPM dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      
      - name: Install dependencies
        id: Npm-install
        run: cd react-2021-09/game-of-life && npm install

      - name: Do linter check
        id: linter
        run: cd react-2021-09/game-of-life && npm run lint

      - name: Run tests
        id: Run-tests
        run: cd react-2021-09/game-of-life && npm run test

      - name: Build project
        id: Project-build
        run: cd react-2021-09/game-of-life && npm run build

      - name: test with-path
        with:
          path: ./react-2021-09/game-of-life
        run: npm run build

