name: Test, Lint, Build and Deploy on Github Pages

on:
  push:
    branches: ["react-2025-08-hw16-shop"]
    # branches: ["master", "main"]

  # Позволяет запустить этот рабочий процесс вручную на вкладке Actions
  workflow_dispatch:

permissions:
  contents: write

jobs:
  project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-2025-08/react-2025-08-hw16-shop

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # Запускаем тесты и линтер
      # - name: Run tests and linter
      #   run: npm run lint && npm test

      - name: Build project
        run: npm run build

      - name: Deploy project to GHP /ponomarenko-alex-otus/react-2025-08/react-2025-08-hw16-shop 🚀
        id: Deploy-Project
        uses: JamesIves/github-pages-deploy-action@4.2.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: react-2025-08/react-2025-08-hw16-shop/dist  # The folder the action should deploy.
          target-folder: react-2025-08/react-2025-08-hw16-shop
          clean: true # Automatically remove deleted files from the deploy branch

      # Останавливаем выполнение строго при неудачных тестах
      # - name: Fail on failed tests
      #   run: |
      #     if [ ${{ job.status }} == 'failure' ]; then exit 1; fi;

  storybook:
    runs-on: ubuntu-latest
    needs: project
    defaults:
      run:
        working-directory: react-2025-08/react-2025-08-hw16-shop

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy Storybook to GHP /ponomarenko-alex-otus/react-2025-08/react-2025-08-hw16-shop/storybook 🚀
        id: Deploy-Storybook
        uses: JamesIves/github-pages-deploy-action@4.2.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: react-2025-08/react-2025-08-hw16-shop/storybook-static  # The folder the action should deploy.
          target-folder: react-2025-08/react-2025-08-hw16-shop/storybook
          clean: true # Automatically remove deleted files from the deploy branch



