// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom': string;
  'root': string;
  'top': string;
  'visible': string;
}
export const cssExports: CssExports;
export default cssExports;
